name: Terminate Environment on PR Close

on:
  pull_request:
    types: [closed]

jobs:
  terminate-environment:
    if: ${{ github.ref != 'refs/heads/main' }}
    uses: ./.github/workflows/terminate-deployment.yaml
    with:
      aws-env: ${{ vars.AWS_EB_APP_NAME }}
      github-env: ${{ github.event.pull_request.head.ref }}